import type { Meta, StoryObj } from "@storybook/react-vite";
import { Button } from "../../../components/ui/button";

const meta = {
  title: "UI/Components/Ui/Button",
  component: Button,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    children: { control: "text" },
    variant: {
      control: { type: "select" },
      options: ["solid", "bordered", "light", "flat", "faded", "shadow", "ghost"],
    },
    color: {
      control: { type: "select" },
      options: ["default", "primary", "secondary", "success", "warning", "danger"],
    },
    size: {
      control: { type: "select" },
      options: ["sm", "md", "lg"],
    },
    radius: {
      control: { type: "select" },
      options: ["none", "sm", "md", "lg", "full"],
    },
    startContent: { control: "text" },
    endContent: { control: "text" },
    spinner: { control: "text" },
    spinnerPlacement: {
      control: { type: "select" },
      options: ["start", "end"],
    },
    fullWidth: { control: "boolean" },
    isIconOnly: { control: "boolean" },
    isDisabled: { control: "boolean" },
    isLoading: { control: "boolean" },
    disableAnimation: { control: "boolean" },
    onPress: { control: "text" },
  },
} satisfies Meta<typeof Button>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    children: "Example content",
    variant: "solid",
    color: "default",
    size: "md",
    radius: "md",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const VariantSolid: Story = {
  args: {
    children: "Example content",
    variant: "solid",
    color: "default",
    size: "sm",
    radius: "md",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const VariantBordered: Story = {
  args: {
    children: "Example content",
    variant: "bordered",
    color: "default",
    size: "md",
    radius: "md",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const VariantLight: Story = {
  args: {
    children: "Example content",
    variant: "light",
    color: "default",
    size: "md",
    radius: "md",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const VariantFlat: Story = {
  args: {
    children: "Example content",
    variant: "flat",
    color: "default",
    size: "md",
    radius: "md",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const VariantFaded: Story = {
  args: {
    children: "Example content",
    variant: "faded",
    color: "default",
    size: "md",
    radius: "md",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const VariantShadow: Story = {
  args: {
    children: "Example content",
    variant: "shadow",
    color: "default",
    size: "md",
    radius: "md",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const VariantGhost: Story = {
  args: {
    children: "Example content",
    variant: "ghost",
    color: "default",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const ColorDefault: Story = {
  args: {
    children: "Example content",
    color: "default",
    variant: "solid",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const ColorPrimary: Story = {
  args: {
    children: "Example content",
    color: "primary",
    variant: "solid",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const ColorSecondary: Story = {
  args: {
    children: "Example content",
    color: "secondary",
    variant: "solid",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const ColorSuccess: Story = {
  args: {
    children: "Example content",
    color: "success",
    variant: "solid",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const ColorWarning: Story = {
  args: {
    children: "Example content",
    color: "warning",
    variant: "solid",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const ColorDanger: Story = {
  args: {
    children: "Example content",
    color: "danger",
    variant: "solid",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const SizeSm: Story = {
  args: {
    children: "Example content",
    size: "sm",
    variant: "solid",
    color: "default",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const SizeMd: Story = {
  args: {
    children: "Example content",
    size: "md",
    variant: "solid",
    color: "default",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const SizeLg: Story = {
  args: {
    children: "Example content",
    size: "lg",
    variant: "solid",
    color: "default",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const RadiusNone: Story = {
  args: {
    children: "Example content",
    radius: "none",
    variant: "solid",
    color: "default",
    size: "sm",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const RadiusSm: Story = {
  args: {
    children: "Example content",
    radius: "sm",
    variant: "solid",
    color: "default",
    size: "sm",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const RadiusMd: Story = {
  args: {
    children: "Example content",
    radius: "md",
    variant: "solid",
    color: "default",
    size: "sm",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const RadiusLg: Story = {
  args: {
    children: "Example content",
    radius: "lg",
    variant: "solid",
    color: "default",
    size: "sm",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const RadiusFull: Story = {
  args: {
    children: "Example content",
    radius: "full",
    variant: "solid",
    color: "default",
    size: "sm",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    spinnerPlacement: "start",
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const SpinnerPlacementStart: Story = {
  args: {
    children: "Example content",
    spinnerPlacement: "start",
    variant: "solid",
    color: "default",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
export const SpinnerPlacementEnd: Story = {
  args: {
    children: "Example content",
    spinnerPlacement: "end",
    variant: "solid",
    color: "default",
    size: "sm",
    radius: "none",
    startContent: undefined,
    endContent: undefined,
    spinner: undefined,
    fullWidth: false,
    isIconOnly: false,
    isDisabled: false,
    isLoading: false,
    disableAnimation: false,
    onPress: undefined,
  },
};
